# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "pl-PL"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
chat:
  auto_reply: true

